<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>EnterpriseAiPlatform.Gateway</AssemblyName>
    <Description>Enterprise AI Platform Linux Data Plane Gateway</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EnterpriseAiPlatform.Gateway</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../EnterpriseAiPlatform.Gateway.Application/EnterpriseAiPlatform.Gateway.Application.csproj" />
    <ProjectReference Include="../EnterpriseAiPlatform.Gateway.Infrastructure/EnterpriseAiPlatform.Gateway.Infrastructure.csproj" />
  </ItemGroup>
</Project>
